### ISSUE TITLE
Add Sequel 4.x support

### ISSUE THREAD

**Issue by voxik** [mislav/will_paginate#333]
Sequel support is not compatible with Sequel 4.x:

```
  1) Sequel::Dataset::Pagination extension pagination should imitate WillPaginate::Collection
     Failure/Error: result = Car.paginate(1, 2)
     NoMethodError:
       undefined method `paginate' for #<Sequel::SQLite::Dataset: "SELECT * FROM `cars`">
     # ./spec/finders/sequel_spec.rb:34:in `block (3 levels) in <top (required)>'
  2) Sequel::Dataset::Pagination extension pagination should perform
     Failure/Error: Car.paginate(1, 2).all.should == [Car[1], Car[2]]
     NoMethodError:
       undefined method `paginate' for #<Sequel::SQLite::Dataset: "SELECT * FROM `cars`">
     # ./spec/finders/sequel_spec.rb:46:in `block (3 levels) in <top (required)>'
  3) Sequel::Dataset::Pagination extension pagination should be empty
     Failure/Error: result = Car.paginate(3, 2)
     NoMethodError:
       undefined method `paginate' for #<Sequel::SQLite::Dataset: "SELECT * FROM `cars`">
     # ./spec/finders/sequel_spec.rb:50:in `block (3 levels) in <top (required)>'
  4) Sequel::Dataset::Pagination extension pagination should perform with #select and #order
     Failure/Error: result = Car.select("name as foo".lit).order(:name).paginate(1, 2).all
     NoMethodError:
       undefined method `lit' for "name as foo":String
     # ./spec/finders/sequel_spec.rb:55:in `block (3 levels) in <top (required)>'
  5) Sequel::Dataset::Pagination extension pagination should perform with #filter
     Failure/Error: results = Car.filter(:name => 'Shelby').paginate(1, 2).all
     NoMethodError:
       undefined method `paginate' for #<Sequel::SQLite::Dataset:0x0000000304b340>
     # ./spec/finders/sequel_spec.rb:61:in `block (3 levels) in <top (required)>'
```

It seems there were done some structural changes in Sequel code: https://github.com/jeremyevans/sequel/compare/3.48.0...4.1.1#diff-101

**Comment by mislav** [comment]
Thanks for reporting. Our test suite tests against Sequel 5.x, and I think earlier Sequel versions might not be supported. I would suggest using newer Sequel.
