### ISSUE TITLE
undefined method `paginate'

### ISSUE THREAD

**Issue by michaelirey** [mislav/will_paginate#356]
Not sure what I may be doing wrong.

I am using `ruby-2.1.0`

Bundle indicates:

```
Using rails (4.0.2)
Using will_paginate (3.0.5)
Using activerecord (4.0.2)
```

Then when I try to paginate:

```
2.1.0 :013 >   User.where('first_name = ?', 'Michael').paginate(:page => 2)
NoMethodError:   User Load (0.6ms)  SELECT `users`.* FROM `users` WHERE (first_name = 'Michael')
undefined method `paginate' for #<ActiveRecord::Relation::ActiveRecord_Relation_User:0x00000108184af8>
        from /Users/michaelirey/.rvm/gems/ruby-2.1.0/gems/activerecord-4.0.2/lib/active_record/relation/delegation.rb:121:in `method_missing'
        from /Users/michaelirey/.rvm/gems/ruby-2.1.0/gems/activerecord-4.0.2/lib/active_record/relation/delegation.rb:68:in `method_missing'
        from (irb):13
        from /Users/michaelirey/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/commands/console.rb:90:in `start'
        from /Users/michaelirey/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/commands/console.rb:9:in `start'
        from /Users/michaelirey/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/commands.rb:62:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by AfolabiOlaoluwa** [comment]
Adding **require 'will_paginate/array'** on my controller solved this problem for me.
