### ISSUE TITLE
3.0.7 and activeadmin 1.0.0pre broken

### ISSUE THREAD

**Issue by dshmelev** [mislav/will_paginate#400]
Hi!
Have a problem with 3.0.7 version (3.0.6 is good).
In case if I have more than one record in activeadmin tables my rails app crashed when load activeadmin controller. Logs:

```
2014-07-05T14:05:19.382623+00:00 app[web.1]: Started GET "/admin/" for 37.203.11.159 at 2014-07-05 14:05:19 +0000
2014-07-05T14:05:19.415267+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.1.0/bundler/gems/active_admin-2ae0a9e09bf9/app/views/active_admin/page/index.html.arb (23.6ms)
2014-07-05T14:05:19.416311+00:00 app[web.1]: cache: [GET /admin/] miss
2014-07-05T14:05:19.386066+00:00 app[web.1]: Processing by Admin::DashboardController#index as HTML
2014-07-05T14:05:19.415702+00:00 app[web.1]: Completed 200 OK in 29ms (Views: 24.5ms | ActiveRecord: 2.6ms)
2014-07-05T14:06:06.789199+00:00 heroku[router]: at=info method=GET path="/admin/site_properties" host=wish-s.herokuapp.com request_id=4e894a6a-ff29-4cc1-854d-a133b2eb57ab fwd="37.203.11.159" 
dyno=web.1 connect=2ms service=61ms status=500 bytes=1798
2014-07-05T14:06:06.734238+00:00 app[web.1]: Started GET "/admin/site_properties" for 37.203.11.159 at 2014-07-05 14:06:06 +0000
2014-07-05T14:06:06.774933+00:00 app[web.1]:   Rendered vendor/bundle/ruby/2.1.0/bundler/gems/active_admin-2ae0a9e09bf9/app/views/active_admin/resource/index.html.arb (31.7ms)
2014-07-05T14:06:06.775111+00:00 app[web.1]: Completed 500 Internal Server Error in 37ms
2014-07-05T14:06:06.782958+00:00 app[web.1]: 
2014-07-05T14:06:06.782965+00:00 app[web.1]: ActionView::Template::Error (wrong number of arguments (0 for 1)):
2014-07-05T14:06:06.782968+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0will_paginate (3.0.7) lib/will_paginate/active_record.rb:149:in `select_for_count'
2014-07-05T14:06:06.782967+00:00 app[web.1]:     1: insert_tag renderer_for(:index)
2014-07-05T14:06:06.782970+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0activerecord (4.1.1) lib/active_record/relation/calculations.rb:203:in `perform_calculation'
2014-07-05T14:06:06.782973+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0activerecord (4.1.1) lib/active_record/relation/calculations.rb:26:in `count'
2014-07-05T14:06:06.782971+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0activerecord (4.1.1) lib/active_record/relation/calculations.r
```

**Comment by voltechs** [comment]
Three years later, any resolution on this?

**Comment by mislav** [comment]
@voltechs I don't think so! We need someone who: 1) explains exactly what's going on, 2) makes a fix, 3) provides a test that fails without the fix.

**Comment by winstonwolff** [comment]
@mislav — For (1) an explanation of what's going on, ActiveRecord defines a method

  [`def select_for_count()`](https://github.com/rails/rails/blob/a1ee43d2170dd6adf5a9f390df2b1dde45018a48/activerecord/lib/active_record/relation/calculations.rb#L384)

 which takes no arguments, but WillPaginate also defines a method with that name and one argument that is mixed into ActiveRecord.

  [`def select_for_count(rel)`](https://github.com/mislav/will_paginate/blob/0b93300d43f658bb15071f59486c92af06aca064/lib/will_paginate/active_record.rb#L140)

The name collision causes things to break.

(2) [This commit](https://github.com/edariedl/will_paginate/commit/5c8db00ecec0dea977da47ea9545b1df4c75d9de) by @edariedl renames WillPaginate's version of the method to avoid the collision

(3) It will take me an hour or two to get everything setup to make a test that shows this problem. Could we just pull this commit in? In the same time, I could just switch to Kaminari.

**Comment by mislav** [comment]
Fixed in https://github.com/mislav/will_paginate/commit/b6fb7b0db9cacb858ab7092a0447ff9db573b9fd#diff-7cb71655df7fd24cccb86712811f0fc8
