### ISSUE TITLE
where condition issue

### ISSUE THREAD

**Issue by victorsosa** [mislav/will_paginate#457]
Hi,

I am trying to execute this query and I got this error:

```
  ArgumentError - wrong number of arguments (2 for 1):
  app/datatables/grades_datatable.rb:46:in `fetch_Grades'
  app/datatables/grades_datatable.rb:39:in `grades'
  app/datatables/grades_datatable.rb:12:in `as_json'
```

```
    notas = Notum.order("#{sort_column} #{sort_direction}")   
    
    if params[:matricula].present? or params[:semestre].present?
      notas = notas.where("matricula like :search or seccion like :semestre", {search: "%#{params[:matricula]}%", semestre: "%#{params[:semestre]}%"})
    end
    notas = notas.paginate(:page => page, :per_page => per_page)
```
So, I can't execute this query using the active record
```
notas.where("matricula like :search or seccion like :semestre", {search: "%#{params[:matricula]}%", semestre: "%#{params[:semestre]}%"})
```
In any case I only can execute the where closure with only one parameter; but as you can see I can't use multiple parameters like I want to. It seen like method is not correctly implemented.
As the doc suggested you have to be able to use more that one placeholder.
http://guides.rubyonrails.org/active_record_querying.html#pure-string-conditions

note: I am using will_paginate_mongoid too

**Comment by victorsosa** [comment]
If I try this:
```
    notas = Notum.order("#{sort_column} #{sort_direction}")   
    notas = notas.paginate(:page => page, :per_page => per_page)
    if params[:matricula].present? or params[:semestre].present?
      notas = notas.where("matricula like :search or seccion like :semestre", {search: "%#{params[:matricula]}%", semestre: "%#{params[:semestre]}%"})
    end
```

I got this error;
```
NoMethodError - undefined method `where' for #<WillPaginate::Collection:0x007fe9a6824be0>:
  app/datatables/grades_datatable.rb:46:in `fetch_Grades'
```

**Comment by victorsosa** [comment]
Bad format condition query,
the correct way of the query is: 
```
notas = notas.where(:semestre => semestre, :seccion => seccion, :tanda => tanda)
```
