### ISSUE TITLE
page_entries_info error

### ISSUE THREAD

**Issue by bplmp** [mislav/will_paginate#556]
When using `page_entries_info` Rails throws the RuntimeError `can't modify frozen Array`.

View:
   
    <%= page_entries_info @places %>

Error:

    can't modify frozen Array

Gemfile:

    ruby '2.4.1'
    gem 'rails', '~> 5.0.2'
    ...
    gem 'will_paginate', github: 'jonatack/will_paginate'

Framework trace:

    /Users/x/.rvm/gems/ruby-2.4.1@railsapp/bundler/gems/will_paginate-3c861498bdbc/lib/will_paginate/view_helpers.rb:171:in `page_entries_info'
    /Users/x/.rvm/gems/ruby-2.4.1@railsapp/bundler/gems/will_paginate-3c861498bdbc/lib/will_paginate/view_helpers/action_view.rb:40:in `page_entries_info'
    actionview (5.0.2) lib/action_view/template.rb:159:in `block in render'
    activesupport (5.0.2) lib/active_support/notifications.rb:166:in `instrument'
    actionview (5.0.2) lib/action_view/template.rb:354:in `instrument'
    actionview (5.0.2) lib/action_view/template.rb:157:in `render'
    actionview (5.0.2) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
    actionview (5.0.2) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
    activesupport (5.0.2) lib/active_support/notifications.rb:164:in `block in instrument'
    activesupport (5.0.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    activesupport (5.0.2) lib/active_support/notifications.rb:164:in `instrument'
    actionview (5.0.2) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
    actionview (5.0.2) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
    actionview (5.0.2) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
    actionview (5.0.2) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
    actionview (5.0.2) lib/action_view/renderer/template_renderer.rb:14:in `render'
    actionview (5.0.2) lib/action_view/renderer/renderer.rb:42:in `render_template'
    actionview (5.0.2) lib/action_view/renderer/renderer.rb:23:in `render'
    actionview (5.0.2) lib/action_view/rendering.rb:104:in `_render_template'
    actionpack (5.0.2) lib/action_controller/metal/streaming.rb:217:in `_render_template'
    actionview (5.0.2) lib/action_view/rendering.rb:83:in `render_to_body'
    actionpack (5.0.2) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
    actionpack (5.0.2) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
    actionpack (5.0.2) lib/abstract_controller/rendering.rb:26:in `render'
    actionpack (5.0.2) lib/action_controller/metal/rendering.rb:36:in `render'
    actionpack (5.0.2) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
    activesupport (5.0.2) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
    /Users/bpl/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
    activesupport (5.0.2) lib/active_support/core_ext/benchmark.rb:12:in `ms'
    actionpack (5.0.2) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
    actionpack (5.0.2) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
    activerecord (5.0.2) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
    actionpack (5.0.2) lib/action_controller/metal/instrumentation.rb:43:in `render'
    actionpack (5.0.2) lib/action_controller/metal/implicit_render.rb:36:in `default_render'
    actionpack (5.0.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
    actionpack (5.0.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
    actionpack (5.0.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
    actionpack (5.0.2) lib/abstract_controller/base.rb:188:in `process_action'
    actionpack (5.0.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
    actionpack (5.0.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
    activesupport (5.0.2) lib/active_support/callbacks.rb:126:in `call'
    activesupport (5.0.2) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
    activesupport (5.0.2) lib/active_support/callbacks.rb:455:in `call'
    activesupport (5.0.2) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
    activesupport (5.0.2) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
    activesupport (5.0.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
    actionpack (5.0.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
    actionpack (5.0.2) lib/action_controller/metal/rescue.rb:20:in `process_action'
    actionpack (5.0.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
    activesupport (5.0.2) lib/active_support/notifications.rb:164:in `block in instrument'
    activesupport (5.0.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    activesupport (5.0.2) lib/active_support/notifications.rb:164:in `instrument'
    actionpack (5.0.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
    actionpack (5.0.2) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
    activerecord (5.0.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
    actionpack (5.0.2) lib/abstract_controller/base.rb:126:in `process'
    actionview (5.0.2) lib/action_view/rendering.rb:30:in `process'
    actionpack (5.0.2) lib/action_controller/metal.rb:190:in `dispatch'
    actionpack (5.0.2) lib/action_controller/metal.rb:262:in `dispatch'
    actionpack (5.0.2) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
    actionpack (5.0.2) lib/action_dispatch/routing/route_set.rb:32:in `serve'
    actionpack (5.0.2) lib/action_dispatch/journey/router.rb:39:in `block in serve'
    actionpack (5.0.2) lib/action_dispatch/journey/router.rb:26:in `each'
    actionpack (5.0.2) lib/action_dispatch/journey/router.rb:26:in `serve'
    actionpack (5.0.2) lib/action_dispatch/routing/route_set.rb:725:in `call'
    warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
    warden (1.2.7) lib/warden/manager.rb:35:in `catch'
    warden (1.2.7) lib/warden/manager.rb:35:in `call'
    rack (2.0.1) lib/rack/etag.rb:25:in `call'
    rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
    rack (2.0.1) lib/rack/head.rb:12:in `call'
    rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
    rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
    actionpack (5.0.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
    activerecord (5.0.2) lib/active_record/migration.rb:553:in `call'
    actionpack (5.0.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
    activesupport (5.0.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
    activesupport (5.0.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
    activesupport (5.0.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
    actionpack (5.0.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
    actionpack (5.0.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
    actionpack (5.0.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
    actionpack (5.0.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
    web-console (3.4.0) lib/web_console/middleware.rb:135:in `call_app'
    web-console (3.4.0) lib/web_console/middleware.rb:28:in `block in call'
    web-console (3.4.0) lib/web_console/middleware.rb:18:in `catch'
    web-console (3.4.0) lib/web_console/middleware.rb:18:in `call'
    actionpack (5.0.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
    railties (5.0.2) lib/rails/rack/logger.rb:36:in `call_app'
    railties (5.0.2) lib/rails/rack/logger.rb:24:in `block in call'
    activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
    activesupport (5.0.2) lib/active_support/tagged_logging.rb:26:in `tagged'
    activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `tagged'
    railties (5.0.2) lib/rails/rack/logger.rb:24:in `call'
    sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
    request_store (1.3.2) lib/request_store/middleware.rb:9:in `call'
    actionpack (5.0.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
    rack (2.0.1) lib/rack/method_override.rb:22:in `call'
    rack (2.0.1) lib/rack/runtime.rb:22:in `call'
    activesupport (5.0.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
    actionpack (5.0.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
    actionpack (5.0.2) lib/action_dispatch/middleware/static.rb:136:in `call'
    rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
    railties (5.0.2) lib/rails/engine.rb:522:in `call'
    puma (3.8.2) lib/puma/configuration.rb:224:in `call'
    puma (3.8.2) lib/puma/server.rb:600:in `handle_request'
    puma (3.8.2) lib/puma/server.rb:435:in `process_client'
    puma (3.8.2) lib/puma/server.rb:299:in `block in run'
    puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by bplmp** [comment]
I was using a fork of the Gem, silly me :rofl:
