### ISSUE TITLE
will_paginate/active_record.rb:140:in `select_for_count'

### ISSUE THREAD

**Issue by grassiricardo** [mislav/will_paginate#611]
Hello guys, 

I am a problem realized process for pagination in the controller.

`paginate(Contact.all)

ArgumentError: wrong number of arguments (given 0, expected 1)
from /Users/alexj.calgaro/.rvm/gems/ruby-2.6.0/gems/will_paginate-3.1.6/lib/will_paginate/active_record.rb:140:in `select_for_count'`

can anybody help me? Thanks

**Comment by grassiricardo** [comment]
Hello, I actualized gem with gem update will_paginate and this problem did be resolved
